[project]
name = "toolkit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "invoke>=2.2.0",
    "netifaces>=0.11.0",
    "scapy>=2.6.1",
]
